dir: "{{.InterfaceDir}}/_mock"
outpkg: mockery
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
with-expecter: true
packages:
  github.com/ideagate/core/adapter/endpoint:
    interfaces:
      IEndpointAdapter:
